import { Show } from '../types/Show';

export const SHOWS: Show[] = [
      {
        id: 1,
        showTitle: 'Survivor',
        gameTitle: 'Got Nothing For Ya',
        centerSquare: 'This is Survivor',
        phrases: [
          'Bring me your torch',
          'Come on in, guys!',
          'Drop your buffs',
          'First look at the new tribe',
          'First things first',
          'Get some water',
          'Got nothing for you',
          'Head back to camp',
          'I\'ll go tally the votes',
          'Immunity idol',
          'It is time to vote',
          'Make Fire',
          'Members of the jury',
          'One in X chance',
          'Rice',
          'Scenes from our next episode',
          'Sole survivor',
          'Survivors ready... go!',
          'Switch tribes',
          'Take your spots',
          'The challenge is on',
          'The tribe has spoken',
          'Time for you to go',
          'Tribal (Council)',
          'Want to see what you\'re playing for?',
          'We\'re Tied',
          'Worth playing for?'
        ]
      },
      {
        id: 2,
        showTitle: 'Toddlers and Tiaras',
        gameTitle: 'Blingo',
        centerSquare: 'Nini is a hard working lady!',
        phrases: [
          '"A" Game',
          'Attitude',
          'Beauty (competition)',
          'Crazy',
          'Crowning',
          'Diva',
          'Doll',
          'Dressing Room',
          'Energy',
          'F-bomb',
          'Facial beauty',
          'Flipper',
          'Grand Supreme',
          'Higher Title',
          'Look at the judges',
          'Money / Cash',
          'Pageant Juice',
          'Pageant Mom',
          'Parent dancing / doing routine',
          'Perfect',
          'Personality',
          'Pixie Sticks',
          'Practice (routine)',
          'Pull (a title)',
          'Rock it',
          'Sparkle',
          'Sparkle',
          'Talent',
          'The Judges',
          'Total Package',
          'Tough Competition',
          'Ultimate',
          'Work it!',
          'Yeah Baby!'
        ]
      },
      {
        id: 3,
        showTitle: 'Top Chef',
        phrases: [
          '(Use of tiny tweezers)',
          'Acidity',
          'Balanced',
          'Behind!',
          'Bon Appetite',
          'Caviar',
          'Course',
          'Crudo',
          'Crunch',
          'Duck',
          'Elevate',
          'Elimination Challenge',
          'Execute / execution',
          'Farm',
          'Flavor Profile',
          'Foam',
          'Guest Judge(s)',
          'Hands Up',
          'Immunity',
          'Judge\'s Table',
          'Mies (en plas)',
          'Pack your knives',
          'Perfect',
          'Pickled',
          'Plate (as a verb)',
          'Please pack your knives and go',
          'Pop',
          'Pressure cooker',
          'Protien',
          'Pull/Draw knives',
          'Quickfire',
          'Ragu',
          'Restaurant Wars',
          'Sophisticated',
          'Sous Vide',
          'Sudden Death',
          'Table',
          'Tare tare',
          'Texture',
          'Today I\'ve made for you',
          'Utensils Down',
          'Your time starts now',
        ]
      },
      {
        id: 4,
        showTitle: 'Ancient Aliens',
        gameTitle: 'Contact!',
        centerSquare: 'AA Theorists Say Yes',
        phrases: [
          'Ancient Aliens',
          'Archaeologist',
          'Carving',
          'Gobekli Tepe',
          'Nazca',
          'Hieroglyph',
          'Mainstream researchers',
          'Maya(n)',
          'Monolith',
          'You have to ask yourself',
          'Legend',
          'Pyramid',
          'Ancient Astronaut Theorists',
          'Extraterrestrial Origins',
          'Sacred Sites',
          'Crystal Skulls',
          'Ancient Technology',
          'Star Gates',
          'Alien DNA',
          'Giorgio Tsoukalos',
          'Underwater Structures',
          'Ancient Space Travel',
          'Lost Civilizations',
          'Mysterious Stone Carvings',
          'Unexplained Phenomena',
          'Ancient Power Plants',
          'Alien Contact'
      ]
      }
    ];
